[package]
name = "demo"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'

[dependencies]
nalgebra = { version = "0.22.0", default-features = false }
wasm-bindgen = "0.2.68"
js-sys = "0.3.45"
wasm-bindgen-futures= "0.4.18"
gloo-events = "0.1.1"
awsm_web = { version = "0.5.8", features = ["tick", "webgl", "loaders", "audio", "serde_iso"], default-features = false }
wee_alloc = { version = "0.4.5", optional = true }
wasm-logger = { version = "0.2.0", optional = true }
shipyard = { version = "0.4.1", features = ["non_send", "non_sync"], default-features = false }
shipyard_scenegraph = { path = "../crate", features = ["easy_deref", "non_send", "non_sync"], default-features = false}
cfg-if = "0.1.10"
log = "0.4.11"
lazy_static = "1.4.0"
console_error_panic_hook = { version = "0.1.6", optional = true }
derive_deref = "1.1.1"

# [patch.crates-io]
# shipyard = { version = "^0.3", features = ["proc", "non_send", "non_sync"], default-features = false}

[dependencies.web-sys]
version = "0.3.45"
features = [
    "console",
    "MouseEvent",
    "Document",
    "Element",
    "HtmlAnchorElement",
    "HtmlElement",
    "HtmlButtonElement",
    "HtmlCanvasElement",
    "CssStyleDeclaration",
    "Node",
    "Window",
    "Performance",

]
[features]
default = ["wee_alloc"]
dev = ["wee_alloc", "wasm-logger", "console_error_panic_hook"]
nalgebra_transforms = ["shipyard_scenegraph/nalgebra_transforms"]
