[package]
name = "shipyard_scenegraph"
version = "0.1.0"
authors = ["David Komer <david.komer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shipyard = { git= "https://github.com/leudz/shipyard.git" }
shipyard_hierarchy = { git= "https://github.com/dakom/shipyard-hierarchy.git" }
thiserror = "1.0.11"
cfg-if = "0.1.10"
nalgebra = {version = "0.19.0", optional = true}

[features]
default = []
nalgebra_transforms = ["nalgebra"]