[package]
name = "shipyard_scenegraph"
version = "0.1.0"
authors = ["David Komer <david.komer@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Scenegraph for Entity Component System"
keywords = ["ecs", "entity", "component", "scenegraph"]
categories = ["concurrency", "game-engines"]
readme = "README.md"
repository = "https://github.com/dakom/shipyard-scenegraph"

[dependencies]
shipyard = { version = "^0.3" }
shipyard_hierarchy = { version = "^0.1" } 
thiserror = "1.0.11"
cfg-if = "0.1.10"
nalgebra = {version = "0.19.0", optional = true}

[features]
default = []
nalgebra_transforms = ["nalgebra"]